// What the editor has selected: an element id, the overlay itself (its canvas and global
// layout), or nothing. Element ids are generated by the database, so they never collide
// with this marker.
export const OVERLAY_SELECTION = "__overlay__";

export type EditorSelection = string | null;
